version: '3.8'

services:
  # ============================================================================
  # DATABASE SERVICES
  # ============================================================================
  
  postgres:
    image: postgres:15-alpine
    container_name: regulens-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-regulens_compliance}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_postgres_password}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./core_infra/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - regulens-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-regulens_compliance}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: regulens-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password} --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - regulens-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # ============================================================================
  # VECTOR DATABASE
  # ============================================================================
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: regulens-qdrant
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "6334:6334"
    networks:
      - regulens-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================================================
  # CORE APPLICATION SERVICES
  # ============================================================================
  
  api:
    build:
      context: .
      dockerfile: core_infra/api/Dockerfile
    container_name: regulens-api
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
      - api_cache:/app/cache
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  regulatory-monitor:
    build:
      context: .
      dockerfile: core_infra/services/regulatory_monitor/Dockerfile
    container_name: regulens-regulatory-monitor
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REGULATORY_MONITOR_ENABLED=${REGULATORY_MONITOR_ENABLED:-true}
      - REGULATORY_MONITOR_INTERVAL_MINUTES=${REGULATORY_MONITOR_INTERVAL_MINUTES:-60}
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
      - qdrant
    restart: unless-stopped

  compliance-engine:
    build:
      context: .
      dockerfile: core_infra/services/compliance_engine/Dockerfile
    container_name: regulens-compliance-engine
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - AML_MONITORING_ENABLED=${AML_MONITORING_ENABLED:-true}
      - TRANSACTION_MONITORING_REAL_TIME=${TRANSACTION_MONITORING_REAL_TIME:-true}
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  ai-insights:
    build:
      context: .
      dockerfile: core_infra/ai/Dockerfile
    container_name: regulens-ai-insights
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - AI_REGULATORY_INSIGHTS_ENABLED=${AI_REGULATORY_INSIGHTS_ENABLED:-true}
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
      - ./models_cache:/app/models_cache
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
      - qdrant
    restart: unless-stopped

  # ============================================================================
  # TASK QUEUE WORKERS
  # ============================================================================
  
  celery-worker:
    build:
      context: .
      dockerfile: core_infra/workers/Dockerfile
    container_name: regulens-celery-worker
    command: celery -A core_infra.workers.celery_app worker --loglevel=info --concurrency=4
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/2
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: core_infra/workers/Dockerfile
    container_name: regulens-celery-beat
    command: celery -A core_infra.workers.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_postgres_password}@postgres:5432/${POSTGRES_DB:-regulens_compliance}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/2
    volumes:
      - ./core_infra:/app/core_infra:ro
      - ./logs:/app/logs
    networks:
      - regulens-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # ============================================================================
  # FRONTEND
  # ============================================================================
  
  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: regulens-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT:-8000}
      - REACT_APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
    volumes:
      - ./ui/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    networks:
      - regulens-network
    depends_on:
      - api
    restart: unless-stopped

  # ============================================================================
  # MONITORING AND OBSERVABILITY
  # ============================================================================
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: regulens-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    networks:
      - regulens-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: regulens-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - regulens-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: regulens-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3001:3000"
    networks:
      - regulens-network
    depends_on:
      - prometheus
    restart: unless-stopped

  # ============================================================================
  # BUSINESS INTELLIGENCE (OPTIONAL)
  # ============================================================================
  
  metabase:
    image: metabase/metabase:latest
    container_name: regulens-metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER:-postgres}
      - MB_DB_PASS=${POSTGRES_PASSWORD:-secure_postgres_password}
      - MB_DB_HOST=postgres
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "3002:3000"
    networks:
      - regulens-network
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - full

  # ============================================================================
  # NGINX REVERSE PROXY (PRODUCTION)
  # ============================================================================
  
  nginx:
    image: nginx:alpine
    container_name: regulens-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - regulens-network
    depends_on:
      - api
      - frontend
    restart: unless-stopped
    profiles:
      - production

# ============================================================================
# NETWORKS
# ============================================================================

networks:
  regulens-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

# ============================================================================
# VOLUMES
# ============================================================================

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  qdrant_data:
    driver: local
  api_cache:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  metabase_data:
    driver: local 