-- Script to add comprehensive table structure comments to all database tables
-- This ensures compliance with Rules.md requirement for proper table documentation

-- Add comments to existing tables for better documentation
COMMENT ON TABLE users IS 'Core user authentication and profile management - Service: Authentication & Authorization Framework';
COMMENT ON COLUMN users.id IS 'Unique user identifier';
COMMENT ON COLUMN users.email IS 'User email address (login credential)';
COMMENT ON COLUMN users.username IS 'Unique username (alternative login)';
COMMENT ON COLUMN users.password_hash IS 'Argon2 hashed password';
COMMENT ON COLUMN users.first_name IS 'User first name';
COMMENT ON COLUMN users.last_name IS 'User last name';
COMMENT ON COLUMN users.phone IS 'Contact phone number';
COMMENT ON COLUMN users.is_active IS 'Account active status';
COMMENT ON COLUMN users.is_verified IS 'Email verification status';
COMMENT ON COLUMN users.last_login_at IS 'Last successful login timestamp';
COMMENT ON COLUMN users.failed_login_attempts IS 'Failed login counter for lockout';
COMMENT ON COLUMN users.locked_until IS 'Account lockout expiration time';
COMMENT ON COLUMN users.password_changed_at IS 'Last password change timestamp';

COMMENT ON TABLE roles IS 'Role-based access control (RBAC) role definitions - Service: Authentication & Authorization Framework';
COMMENT ON COLUMN roles.id IS 'Unique role identifier';
COMMENT ON COLUMN roles.name IS 'Role name (e.g., admin, analyst)';
COMMENT ON COLUMN roles.description IS 'Human-readable role description';
COMMENT ON COLUMN roles.is_system_role IS 'System-defined vs user-defined role';
COMMENT ON COLUMN roles.permissions IS 'Array of permission strings';

COMMENT ON TABLE user_roles IS 'User-role assignments for RBAC - Service: Authentication & Authorization Framework';
COMMENT ON COLUMN user_roles.user_id IS 'Reference to users table';
COMMENT ON COLUMN user_roles.role_id IS 'Reference to roles table';
COMMENT ON COLUMN user_roles.granted_by IS 'User who granted this role';
COMMENT ON COLUMN user_roles.granted_at IS 'Role assignment timestamp';
COMMENT ON COLUMN user_roles.expires_at IS 'Role expiration timestamp';
COMMENT ON COLUMN user_roles.is_active IS 'Role assignment active status';

COMMENT ON TABLE organizations IS 'Organization master data - Service: Shared across all services';
COMMENT ON COLUMN organizations.id IS 'Unique organization identifier';
COMMENT ON COLUMN organizations.name IS 'Organization display name';
COMMENT ON COLUMN organizations.legal_name IS 'Legal entity name';
COMMENT ON COLUMN organizations.registration_number IS 'Business registration number';
COMMENT ON COLUMN organizations.tax_id IS 'Tax identification number';
COMMENT ON COLUMN organizations.industry IS 'Industry classification';
COMMENT ON COLUMN organizations.country IS 'Country of incorporation';
COMMENT ON COLUMN organizations.address IS 'Organization address information';
COMMENT ON COLUMN organizations.contact_info IS 'Organization contact details';
COMMENT ON COLUMN organizations.is_active IS 'Organization active status';

COMMENT ON TABLE audit_logs IS 'System audit trail for all operations - Service: Shared across all services';
COMMENT ON COLUMN audit_logs.id IS 'Unique audit log identifier';
COMMENT ON COLUMN audit_logs.entity_type IS 'Type of entity being audited';
COMMENT ON COLUMN audit_logs.entity_id IS 'ID of entity being audited';
COMMENT ON COLUMN audit_logs.action IS 'Action performed (CREATE, UPDATE, DELETE)';
COMMENT ON COLUMN audit_logs.old_values IS 'Previous values before change';
COMMENT ON COLUMN audit_logs.new_values IS 'New values after change';
COMMENT ON COLUMN audit_logs.user_id IS 'User who performed the action';
COMMENT ON COLUMN audit_logs.ip_address IS 'IP address of the request';
COMMENT ON COLUMN audit_logs.user_agent IS 'User agent string';
COMMENT ON COLUMN audit_logs.correlation_id IS 'Request correlation ID';
COMMENT ON COLUMN audit_logs.service_name IS 'Service that generated the audit log';

COMMENT ON TABLE customers IS 'Customer master data for AML and compliance - Service: AML Service';
COMMENT ON COLUMN customers.id IS 'Unique customer identifier';
COMMENT ON COLUMN customers.organization_id IS 'Associated organization (if applicable)';
COMMENT ON COLUMN customers.customer_type IS 'Customer classification (INDIVIDUAL/BUSINESS)';
COMMENT ON COLUMN customers.first_name IS 'Individual customer first name';
COMMENT ON COLUMN customers.last_name IS 'Individual customer last name';
COMMENT ON COLUMN customers.date_of_birth IS 'Individual customer birth date';
COMMENT ON COLUMN customers.nationality IS 'ISO 3166-1 alpha-3 country code';
COMMENT ON COLUMN customers.identification_documents IS 'Array of ID documents (passport, license, etc.)';
COMMENT ON COLUMN customers.address IS 'Customer address information';
COMMENT ON COLUMN customers.contact_info IS 'Email, phone, and other contact details';
COMMENT ON COLUMN customers.risk_score IS 'Calculated risk score (0-100)';
COMMENT ON COLUMN customers.risk_level IS 'Risk classification (LOW/MEDIUM/HIGH/CRITICAL)';
COMMENT ON COLUMN customers.pep_status IS 'Politically Exposed Person status';
COMMENT ON COLUMN customers.sanctions_status IS 'Sanctions list match status';
COMMENT ON COLUMN customers.kyc_status IS 'KYC verification status';
COMMENT ON COLUMN customers.kyc_completed_at IS 'KYC completion timestamp';
COMMENT ON COLUMN customers.last_reviewed_at IS 'Last risk review timestamp';
COMMENT ON COLUMN customers.next_review_due IS 'Next scheduled risk review date';

COMMENT ON TABLE transactions IS 'Financial transaction records for monitoring - Service: AML Service';
COMMENT ON COLUMN transactions.id IS 'Unique transaction identifier';
COMMENT ON COLUMN transactions.customer_id IS 'Reference to customer who initiated transaction';
COMMENT ON COLUMN transactions.transaction_type IS 'Type of transaction (WIRE, ACH, CASH, etc.)';
COMMENT ON COLUMN transactions.amount IS 'Transaction amount in specified currency';
COMMENT ON COLUMN transactions.currency IS 'ISO 4217 currency code';
COMMENT ON COLUMN transactions.description IS 'Transaction description or memo';
COMMENT ON COLUMN transactions.counterparty_name IS 'Name of transaction counterparty';
COMMENT ON COLUMN transactions.counterparty_account IS 'Counterparty account number';
COMMENT ON COLUMN transactions.counterparty_bank IS 'Counterparty bank name';
COMMENT ON COLUMN transactions.counterparty_country IS 'Counterparty country code';
COMMENT ON COLUMN transactions.transaction_date IS 'Transaction execution timestamp';
COMMENT ON COLUMN transactions.value_date IS 'Transaction value date';
COMMENT ON COLUMN transactions.reference_number IS 'Transaction reference number';
COMMENT ON COLUMN transactions.channel IS 'Transaction channel (ONLINE, BRANCH, ATM, etc.)';
COMMENT ON COLUMN transactions.risk_score IS 'Calculated transaction risk score';
COMMENT ON COLUMN transactions.risk_factors IS 'Array of risk factors identified';
COMMENT ON COLUMN transactions.is_suspicious IS 'Suspicious activity flag';
COMMENT ON COLUMN transactions.alert_generated IS 'Alert generation flag';
COMMENT ON COLUMN transactions.status IS 'Transaction processing status';
COMMENT ON COLUMN transactions.processed_at IS 'Transaction processing completion timestamp';

COMMENT ON TABLE sanctions_lists IS 'Sanctions and watchlist entries - Service: AML Service';
COMMENT ON COLUMN sanctions_lists.id IS 'Unique sanctions entry identifier';
COMMENT ON COLUMN sanctions_lists.list_name IS 'Name of sanctions list (OFAC SDN, EU, etc.)';
COMMENT ON COLUMN sanctions_lists.source IS 'Source of sanctions data';
COMMENT ON COLUMN sanctions_lists.entity_type IS 'Type of sanctioned entity (INDIVIDUAL/ORGANIZATION)';
COMMENT ON COLUMN sanctions_lists.entity_name IS 'Name of sanctioned entity';
COMMENT ON COLUMN sanctions_lists.aliases IS 'Array of known aliases';
COMMENT ON COLUMN sanctions_lists.addresses IS 'Array of known addresses';
COMMENT ON COLUMN sanctions_lists.identifiers IS 'Array of identification numbers';
COMMENT ON COLUMN sanctions_lists.sanctions_type IS 'Type of sanctions applied';
COMMENT ON COLUMN sanctions_lists.listing_date IS 'Date entity was added to list';
COMMENT ON COLUMN sanctions_lists.last_updated IS 'Last update timestamp';
COMMENT ON COLUMN sanctions_lists.is_active IS 'Active status of sanctions entry';

COMMENT ON TABLE aml_alerts IS 'AML compliance alerts and investigations - Service: AML Service';
COMMENT ON COLUMN aml_alerts.id IS 'Unique alert identifier';
COMMENT ON COLUMN aml_alerts.alert_type IS 'Type of alert (HIGH_VALUE, VELOCITY, etc.)';
COMMENT ON COLUMN aml_alerts.severity IS 'Alert severity level';
COMMENT ON COLUMN aml_alerts.customer_id IS 'Reference to customer (if applicable)';
COMMENT ON COLUMN aml_alerts.transaction_id IS 'Reference to transaction (if applicable)';
COMMENT ON COLUMN aml_alerts.rule_name IS 'Name of rule that triggered alert';
COMMENT ON COLUMN aml_alerts.description IS 'Alert description';
COMMENT ON COLUMN aml_alerts.risk_score IS 'Risk score that triggered alert';
COMMENT ON COLUMN aml_alerts.status IS 'Alert status (OPEN, INVESTIGATING, CLOSED)';
COMMENT ON COLUMN aml_alerts.assigned_to IS 'User assigned to investigate alert';
COMMENT ON COLUMN aml_alerts.investigation_notes IS 'Investigation notes and findings';
COMMENT ON COLUMN aml_alerts.resolution IS 'Alert resolution details';
COMMENT ON COLUMN aml_alerts.closed_at IS 'Alert closure timestamp';
COMMENT ON COLUMN aml_alerts.escalated_at IS 'Alert escalation timestamp';

COMMENT ON TABLE policies IS 'Compliance policy management - Service: Compliance Service';
COMMENT ON COLUMN policies.id IS 'Unique policy identifier';
COMMENT ON COLUMN policies.title IS 'Policy title';
COMMENT ON COLUMN policies.description IS 'Policy description';
COMMENT ON COLUMN policies.policy_type IS 'Type of policy (SECURITY, PRIVACY, etc.)';
COMMENT ON COLUMN policies.content IS 'Policy content and procedures';
COMMENT ON COLUMN policies.version IS 'Policy version number';
COMMENT ON COLUMN policies.status IS 'Policy status (DRAFT, ACTIVE, RETIRED)';
COMMENT ON COLUMN policies.effective_date IS 'Policy effective date';
COMMENT ON COLUMN policies.review_date IS 'Next scheduled review date';
COMMENT ON COLUMN policies.approved_by IS 'User who approved policy';
COMMENT ON COLUMN policies.approved_at IS 'Policy approval timestamp';
COMMENT ON COLUMN policies.tags IS 'Policy classification tags';

COMMENT ON TABLE controls IS 'Compliance control framework - Service: Compliance Service';
COMMENT ON COLUMN controls.id IS 'Unique control identifier';
COMMENT ON COLUMN controls.control_id IS 'Control reference ID';
COMMENT ON COLUMN controls.title IS 'Control title';
COMMENT ON COLUMN controls.description IS 'Control description';
COMMENT ON COLUMN controls.control_type IS 'Control type (PREVENTIVE/DETECTIVE/CORRECTIVE)';
COMMENT ON COLUMN controls.frequency IS 'Control execution frequency';
COMMENT ON COLUMN controls.owner_id IS 'Control owner user ID';
COMMENT ON COLUMN controls.policy_id IS 'Reference to related policy';
COMMENT ON COLUMN controls.implementation_status IS 'Control implementation status';
COMMENT ON COLUMN controls.effectiveness IS 'Control effectiveness rating';
COMMENT ON COLUMN controls.last_tested IS 'Last control test date';
COMMENT ON COLUMN controls.next_test_due IS 'Next scheduled test date';
COMMENT ON COLUMN controls.evidence_requirements IS 'Required evidence for control testing';

COMMENT ON TABLE control_tests IS 'Control testing and validation records - Service: Compliance Service';
COMMENT ON COLUMN control_tests.id IS 'Unique test record identifier';
COMMENT ON COLUMN control_tests.control_id IS 'Reference to tested control';
COMMENT ON COLUMN control_tests.test_date IS 'Date of control test';
COMMENT ON COLUMN control_tests.tester_id IS 'User who performed test';
COMMENT ON COLUMN control_tests.test_method IS 'Testing methodology used';
COMMENT ON COLUMN control_tests.sample_size IS 'Sample size for testing';
COMMENT ON COLUMN control_tests.results IS 'Test results and findings';
COMMENT ON COLUMN control_tests.effectiveness_rating IS 'Control effectiveness rating';
COMMENT ON COLUMN control_tests.deficiencies IS 'Identified deficiencies';
COMMENT ON COLUMN control_tests.recommendations IS 'Recommendations for improvement';
COMMENT ON COLUMN control_tests.evidence_collected IS 'Evidence collected during testing';
COMMENT ON COLUMN control_tests.next_test_date IS 'Next scheduled test date';
